-- MySQL Script generated by MySQL Workbench
-- Mon Jan 18 19:38:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema caniada
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `caniada` ;

-- -----------------------------------------------------
-- Schema caniada
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `caniada` DEFAULT CHARACTER SET utf8 ;
USE `caniada` ;

-- -----------------------------------------------------
-- Table `caniada`.`colores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caniada`.`colores` ;

CREATE TABLE IF NOT EXISTS `caniada`.`colores` (
  `id_color` INT NOT NULL AUTO_INCREMENT,
  `nombre_color` VARCHAR(45) NULL,
  PRIMARY KEY (`id_color`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caniada`.`generos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caniada`.`generos` ;

CREATE TABLE IF NOT EXISTS `caniada`.`generos` (
  `id_genero` INT NOT NULL AUTO_INCREMENT,
  `nombre_genero` VARCHAR(45) NULL,
  PRIMARY KEY (`id_genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caniada`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caniada`.`categorias` ;

CREATE TABLE IF NOT EXISTS `caniada`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NULL,
  `estado` VARCHAR(1) NOT NULL DEFAULT('1'),
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caniada`.`talles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caniada`.`talles` ;

CREATE TABLE IF NOT EXISTS `caniada`.`talles` (
  `id_talle` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_talle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caniada`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caniada`.`productos` ;

CREATE TABLE IF NOT EXISTS `caniada`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `sku` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` TEXT(300) NULL,
  `precio` DECIMAL(5,2) NULL,
  `cantidad` INT NULL,
  `imagen_1` VARCHAR(45) NULL,
  `imagen_2` VARCHAR(45) NULL,
  `imagen_3` VARCHAR(45) NULL,
  `imagen_4` VARCHAR(45) NULL,
  `id_color` INT NOT NULL,
  `id_genero` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  `id_talle` INT NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id_producto`, `sku`),
  INDEX `fk_productos_colores_idx` (`id_color` ASC) ,
  INDEX `fk_productos_generos1_idx` (`id_genero` ASC) ,
  INDEX `fk_productos_categorias1_idx` (`id_categoria` ASC) ,
  INDEX `fk_productos_talles1_idx` (`id_talle` ASC) ,
  CONSTRAINT `fk_productos_colores`
    FOREIGN KEY (`id_color`)
    REFERENCES `caniada`.`colores` (`id_color`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_generos1`
    FOREIGN KEY (`id_genero`)
    REFERENCES `caniada`.`generos` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_categorias1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `caniada`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_talles1`
    FOREIGN KEY (`id_talle`)
    REFERENCES `caniada`.`talles` (`id_talle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caniada`.`paises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caniada`.`paises` ;

CREATE TABLE IF NOT EXISTS `caniada`.`paises` (
  `id_pais` INT NOT NULL AUTO_INCREMENT,
  `nombre_pais` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caniada`.`provincias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caniada`.`provincias` ;

CREATE TABLE IF NOT EXISTS `caniada`.`provincias` (
  `id_provincia` INT NOT NULL AUTO_INCREMENT,
  `nombre_provincia` VARCHAR(45) NULL,
  `paises_id_pais` INT NOT NULL,
  PRIMARY KEY (`id_provincia`),
  INDEX `fk_provincias_paises1_idx` (`paises_id_pais` ASC) ,
  CONSTRAINT `fk_provincias_paises1`
    FOREIGN KEY (`paises_id_pais`)
    REFERENCES `caniada`.`paises` (`id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caniada`.`ciudades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caniada`.`ciudades` ;

CREATE TABLE IF NOT EXISTS `caniada`.`ciudades` (
  `id_ciudad` INT NOT NULL AUTO_INCREMENT,
  `nombre_ciudad` VARCHAR(45) NULL,
  `provincias_id_provincia` INT NOT NULL,
  PRIMARY KEY (`id_ciudad`),
  INDEX `fk_ciudades_provincias1_idx` (`provincias_id_provincia` ASC) ,
  CONSTRAINT `fk_ciudades_provincias1`
    FOREIGN KEY (`provincias_id_provincia`)
    REFERENCES `caniada`.`provincias` (`id_provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caniada`.`formas_de_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caniada`.`formas_de_pago` ;

CREATE TABLE IF NOT EXISTS `caniada`.`formas_de_pago` (
  `id_forma` INT NOT NULL AUTO_INCREMENT,
  `nombre_forma` VARCHAR(45) NULL,
  `cuota` INT NULL,
  PRIMARY KEY (`id_forma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caniada`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caniada`.`roles` ;

CREATE TABLE IF NOT EXISTS `caniada`.`roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caniada`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caniada`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `caniada`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(99) NULL,
  `avatar` VARCHAR(50) NULL DEFAULT NULL,
  `id_rol` INT NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuarios_roles1_idx` (`id_rol` ASC) ,
  CONSTRAINT `fk_usuarios_roles1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `caniada`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caniada`.`Descuentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caniada`.`Descuentos` ;

CREATE TABLE IF NOT EXISTS `caniada`.`Descuentos` (
  `id_descuento` INT NOT NULL AUTO_INCREMENT,
  `nombre_descuento` VARCHAR(45) NULL,
  `porcentaje_descuento` INT NULL,
  PRIMARY KEY (`id_descuento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caniada`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caniada`.`ventas` ;

CREATE TABLE IF NOT EXISTS `caniada`.`ventas` (
  `id_venta` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `fecha_venta` DATETIME NULL,
  `monto_parcial` DECIMAL(5,2) NULL,
  `monto_total` DECIMAL(5,2) NULL,
  `calle_envio` VARCHAR(45) NULL,
  `numero_calle_envio` INT NULL,
  `codigo_postal` INT NULL,
  `id_ciudad` INT NOT NULL,
  `id_forma_pago` INT NOT NULL,
  `id_descuento` INT NOT NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `fk_ventas_ciudades1_idx` (`id_ciudad` ASC) ,
  INDEX `fk_ventas_formas_de_pago1_idx` (`id_forma_pago` ASC) ,
  INDEX `fk_ventas_usuarios1_idx` (`id_usuario` ASC) ,
  INDEX `fk_ventas_Descuentos1_idx` (`id_descuento` ASC) ,
  CONSTRAINT `fk_ventas_ciudades1`
    FOREIGN KEY (`id_ciudad`)
    REFERENCES `caniada`.`ciudades` (`id_ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_formas_de_pago1`
    FOREIGN KEY (`id_forma_pago`)
    REFERENCES `caniada`.`formas_de_pago` (`id_forma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `caniada`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_Descuentos1`
    FOREIGN KEY (`id_descuento`)
    REFERENCES `caniada`.`Descuentos` (`id_descuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caniada`.`detalles_ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caniada`.`detalles_ventas` ;

CREATE TABLE IF NOT EXISTS `caniada`.`detalles_ventas` (
  `id_detalle` INT NOT NULL AUTO_INCREMENT,
  `id_venta` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `sku` INT NOT NULL,
  `cantidad` INT NULL,
  `monto_parcial` DECIMAL(5,2) NULL,
  PRIMARY KEY (`id_detalle`, `id_venta`),
  INDEX `fk_detalles_ventas_productos1_idx` (`id_producto` ASC, `sku` ASC) ,
  INDEX `fk_detalles_ventas_ventas1_idx` (`id_venta` ASC) ,
  CONSTRAINT `fk_detalles_ventas_productos1`
    FOREIGN KEY (`id_producto` , `sku`)
    REFERENCES `caniada`.`productos` (`id_producto` , `sku`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalles_ventas_ventas1`
    FOREIGN KEY (`id_venta`)
    REFERENCES `caniada`.`ventas` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caniada`.`permisos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caniada`.`permisos` ;

CREATE TABLE IF NOT EXISTS `caniada`.`permisos` (
  `id_permiso` INT NOT NULL AUTO_INCREMENT,
  `nombre_permiso` VARCHAR(45) NULL,
  PRIMARY KEY (`id_permiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caniada`.`permisos_x_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caniada`.`permisos_x_rol` ;

CREATE TABLE IF NOT EXISTS `caniada`.`permisos_x_rol` (
  `id_permiso` INT NOT NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_permiso`, `id_rol`),
  INDEX `fk_permisos_x_rol_roles1_idx` (`id_rol` ASC) ,
  CONSTRAINT `fk_permisos_x_rol_permisos1`
    FOREIGN KEY (`id_permiso`)
    REFERENCES `caniada`.`permisos` (`id_permiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permisos_x_rol_roles1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `caniada`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;